server:
  host: "0.0.0.0"
  port: 8080
  mode: "debug"

database:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "1234qwer"
  name: "blog_db"
  max_open_conns: 20
  max_idle_conns: 10
  conn_max_lifetime_minutes: 60

jwt:
  secret: "RcbvlaTZIP0p7I6C"
  expire_hour: 24
  issuer: "homework4-blog"

log:
  level: "info"
